### ISSUE TITLE
Initial GPS

### ISSUE THREAD

**Issue by b6oy** [AeonLucid/POGOLib#1]
Hello,
Nice work here. It looks to me the initial GPS is not parsed correctly.
I wrote test code for the pokestops/ fortsearch.

**Comment by AeonLucid** [comment]
It parses correctly for me, can you show what's wrong?

**Comment by b6oy** [comment]
removed ?.Replace(".", ","); and worked fine.
when i was inputting 40.1234 it will be saved as 401234.
