### ISSUE TITLE
Invalid exception @ EnvelopedResponse

### ISSUE THREAD

**Issue by N3messys** [AeonLucid/POGOLib#11]
The exception thrown [here](https://github.com/AeonLucid/POGOLib/blob/master/POGOLib/Net/RPCClient.cs#L310-L311) is invalid in some cases.
For example, consider the following request + response
```csharp
public static FortSearchResponse SearchFort(this Session session, FortData fort)
{
	var searchRequest = new Request
	{
		RequestType = RequestType.FortSearch,
		RequestMessage = new FortSearchMessage
		{
			FortId = fort.Id,
			PlayerLatitude = session.Player.Latitude,
			PlayerLongitude = session.Player.Longitude,
			FortLatitude = fort.Latitude,
			FortLongitude = fort.Longitude
		}.ToByteString()
	};

	var searchReponseBytes = session.RpcClient.SendRemoteProcedureCall(searchRequest);
	var searchResponse = FortSearchResponse.Parser.ParseFrom(searchReponseBytes);

	return searchResponse;
}
```
The server is going to return only 1 response, even though multiple requests have been done, thus throwing the mentioned exception.

As far as I can tell, the added requests are there so that the server can mimic asynchronicity, but I'm not sure if adding 4 requests to each manual request done is the good way of achieving this.

**Comment by MajdajkD** [comment]
Hi, this error is intended, you are making a bad request.
The correct way to do this:


            var encounterResponse = session.RpcClient.SendRemoteProcedureCall(new Request
            {
                RequestType = RequestType.FortDetails,
                RequestMessage = new FortDetailsMessage
                {
                    FortId = fort.Id,
                    Latitude = fort.Latitude,
                    Longitude = fort.Longitude
                }.ToByteString()
            });
            var responseMessage = FortDetailsResponse.Parser.ParseFrom(encounterResponse);

            var spinResponse = session.RpcClient.SendRemoteProcedureCall(new Request
            {
                RequestType = RequestType.FortSearch,
                RequestMessage = new FortSearchMessage
                {
                    FortId = fort.Id,
                    FortLatitude = fort.Latitude,
                    FortLongitude = fort.Longitude,
                    PlayerLatitude = session.Player.Latitude,
                    PlayerLongitude = session.Player.Longitude
                }.ToByteString()
            });

            var spinResponseMessage = FortSearchResponse.Parser.ParseFrom(spinResponse);

**Comment by Lennix** [comment]
Adding the 4 default requests is client-like behavior
