### ISSUE TITLE
Incorrect InventoryDelta implementation

### ISSUE THREAD

**Issue by Lizzaran** [AeonLucid/POGOLib#15]
This issues serves solely as "_documentation_", I probably will push an pull request soon.

RPCClient.HandleDefaultResponses updates the inventory, although only on the initial execution the full inventory gets send. Further responses only send the changed / affected entries, therefore after actions which affects the inventory (e.g. Exp gain, Item usage etc.) it becomes "invalid".

**Comment by pingec** [comment]
Yes this definitely needs fixing. Until it's fixed, a (bad) workaround is to do a full refresh of inventory in the getter by doing a request like so
```
                    RequestMessage = new GetInventoryMessage
                    {
                       LastTimestampMs = 0
                    }
```

**Comment by pingec** [comment]
See https://github.com/AeonLucid/POGOLib/pull/18#issuecomment-235381968

**Comment by awmoeder** [comment]
This fix has a little side effect and will never update the Player Stats.

Change Player.InventoryOnUpdate method will solve the problem
```cs
        private void InventoryOnUpdate(object sender, EventArgs eventArgs)
        {
            var stats = Inventory?.InventoryItems?.Where(i => i.InventoryItemData.PlayerStats!= null).FirstOrDefault()?.InventoryItemData?.PlayerStats;
            if (stats != null)
            {
                Stats = stats;
            }
        }
```

**Comment by pingec** [comment]
```
InventoryItems.AddRange(delta.InventoryItems.Where(i => i != null));
```
This works ok.
