### ISSUE TITLE
Pokemon Trainer Club - Check if is verified

### ISSUE THREAD

**Issue by Lizzaran** [AeonLucid/POGOLib#17]
If a PTC account isn't verified it will fail and throw an error.
Login should check if the account is verified, if not throw a custom execption.

**Comment by AeonLucid** [comment]
What if someone just wants to use his acc for 2 days? Maybe a warning message is a better idea?

**Comment by Lennix** [comment]
Isn't a "NotVeriedException" a way to print a warning message?
