### ISSUE TITLE
responseEnvelope.StatusCode 3

### ISSUE THREAD

**Issue by awmoeder** [AeonLucid/POGOLib#21]
When I send a CatchPokemon request. I always get a statuscode 3 as response.
The responseEnvelope.Returns.Count is only 1 so the request fails.

Does anyone know how to react to a statuscode 3?

**Comment by pingec** [comment]
I think code 3 might mean a bad request. This is just my speculation. If the issue started occurring recently it's probably because servers are unstable right now and just wait it out. If it persists you might be sending bad requests.

**Comment by awmoeder** [comment]
It is possible that this a server side issue. Because the request randomly fails with an statuscode 3. Other times I send the same request and it succeeds.

Is there someone else who has experienced the same thing?

**Comment by MajdajkD** [comment]
I was experiencing this until I figured out, that i need to send a pokemonencounter request right before the catchpokemon request. (like the fortdetails-> fortsearch duo). If you don't send the encounter(or details at the fort) request, there is a good chance to get bad request error from the server.

**Comment by AeonLucid** [comment]
You need to send an encounter first.

**Comment by awmoeder** [comment]
I do send an encouter first followed by a catch request. The encounter always works. But when I send the catch request, I randomly get the response code 3.

**Comment by pingec** [comment]
Come to https://pkre.slack.com/messages/pogolib-csharp/ and we can try your code

**Comment by awmoeder** [comment]
I have solved my problem. I tried to catch a pokemon while I had no pokeballs left.
Now I have another situation that causes the status code 3 as response. When I send a UseItemPotion request, I always get the status code 3.
This is the code that causes this error.

```cs
		public UseItemPotionResponse HealPokemon(ItemId item, PokemonData pokemon)
		{
			UseItemPotionResponse response = null;
			try
			{
				var responseBytestring = CurrentSession.RpcClient.SendRemoteProcedureCall(new Request
				{
					RequestType = RequestType.UseItemPotion,
					RequestMessage = new UseItemPotionMessage
					{
						ItemId = item,
						PokemonId = pokemon.Id
					}.ToByteString()
				});

				try
				{
					response = UseItemPotionResponse.Parser.ParseFrom(responseBytestring);
				}
				catch (InvalidProtocolBufferException e)
				{
					Log.Error(e.ToString());
					return response;
				}

				return response;
			}
			catch (Exception ex)
			{
				Log.Error("Exception on HealPokemon: " + ex.ToString());
				return null;
			}
		}
```
Anyone knows what I do wrong?
