### ISSUE TITLE
Can I please get the previous version + inventory update without everything changed?

### ISSUE THREAD

**Issue by sodanakin** [AeonLucid/POGOLib#23]
The code below WORKED until that new update. Basically nothing really works for me atm.  Is there anyway I can get only that Inventory fix and nothing else (Getting null reference exceptions on last version for items) Anyhow hope someone can help me with this soon been trying to get my app back to work for almost 2 days now due to that update to the lib.....

`                    var teaminfo = session.RpcClient.SendRemoteProcedureCall(new Request { RequestType = RequestType.GetPlayer, RequestMessage = new GetPlayerMessage { }.ToByteString() });`

                        ```
throw new Exception(
                            "Received a non-success HTTP status code from the RPC server, see the console for the response.");
```

**Comment by sodanakin** [comment]
Another solution would be to tell me why

`                            if (item.InventoryItemData.Item.Count >= 0) //items 2
                            {
                                string itemid = item.InventoryItemData.Item.ItemId.ToString();
                                string itemcount = item.InventoryItemData.Item.Count.ToString();
                                InventoryHelper_Items(itemid, itemcount);
                            }`


Doesn't work in the previous version.

**Comment by pingec** [comment]
What are you trying to accomplish?

**Comment by sodanakin** [comment]
@pingec  I am trying (In the previous version, latest doesn't work at all for me) to get the ItemID and Count for every item in session.Player.Inventory.InventoryItems

**Comment by Lizzaran** [comment]
```
public static List<ItemData> GetItems(this Inventory inventory)
        {
            return
                inventory?.InventoryItems?.Select(it => it?.InventoryItemData?.Item)
                    .Where(i => i != null && i.ItemId > 0)
                    .ToList() ?? new List<ItemData>();
        }
```
