### ISSUE TITLE
Disconnect the Session?

### ISSUE THREAD

**Issue by Eliminster0** [AeonLucid/POGOLib#24]
Is the something like a session.Shutdown()? I know there isn't that exact one but a similar functionally (besides killing the loop). I did not see anything in RequestMessages either for something like this. I have the startup code from the Demo shoved into a function that gets called from the HandleCommands loop, and would like to add a disconnect command so a user could log out without closing the window and change the passed arguments to the StartUp. BTW great work on the API, once I get more familiar with it and setup some basic stuff I am hoping to wrap it all up inside an Xna project.

**Comment by Eliminster0** [comment]
[Hit Play and Just Jam](http://downloads.khinsider.com/game-soundtracks/album/pokemon-ten-years-of-pokemon/1-pokemon-theme-season-theme-.mp3)

**Comment by Lizzaran** [comment]
Currently there isn't a "Shutdown" method implemented, although it would be easy to add it.
You can always open a pull request :tongue:

**Comment by Eliminster0** [comment]
Lol I would love to do it, though I am not sure how you would do it... I think you would need to just disco from the google services....

**Comment by Lizzaran** [comment]
@Eliminster0 
Basically you just need to stop the heartbeat, there isn't any "real" way to logout. I will push an update once I fixed the inventory for deleted stuff.

**Comment by Eliminster0** [comment]
Yes that what I have did originally, however, the TCP connection with the server persists.
` public static void ShowActiveTcpConnections()
        {
            Console.WriteLine("Active TCP Connections Endpoints");
            foreach(var c in IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections())
            {
                if (c.State.Equals(TcpState.Established))
                {
                    switch (c.RemoteEndPoint.Address.ToString())
                    {
                        case "130.211.14.80":
                            Console.WriteLine(Dns.GetHostEntry(c.RemoteEndPoint.Address));
                            Console.WriteLine(c.RemoteEndPoint.Address.ToString());
                            break;
                        case "::1":
                        case "127.0.0.1":
                            break;
                        default:
                            Console.WriteLine(c.RemoteEndPoint.Address.ToString());
                            break;
                    }
                }
            }
        }`
Now I have looked for a way to revoke token using 
` public static async void GiveBackToken(AccessToken token)
        {
            try
            {
                var values = new Dictionary<string, string> { { "token", token.Token } };
                //var content = new FormUrlEncodedContent(values);

                HttpClient client = new HttpClient();
                var response = 
                    await client.GetAsync("https://accounts.google.com/o/oauth2/revoke?token=" + WebUtility.UrlEncode(token.Token));
                // var response = 
                         await client.PostAsync("https://accounts.google.com/o/oauth2/revoke?token=", content);

                var responseString = await response.Content.ReadAsStringAsync();
                Log.Info(responseString);
            }
            catch (IOException e)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Log.Fatal(e.StackTrace);
                Console.ForegroundColor = ConsoleColor.Gray;
            }`   

But the response comes back "error:" "invalid token".  I am not sure how to get the actual status code from the response message.

**Comment by Eliminster0** [comment]
Ok, so I "invented" a more hacky way of killing the session without having to stop the heartbeat **explicitly**  and without handing the token back to the authentication server.  

As far as my thoughts on the token turn part is that `"https://accounts.google.com/o/oauth2/revoke?token="` is not the right turn in point for the tokens, however this is just speculation.

To start off we have the Disconnect Method:

```
public static void Disconnect() {
     //If we are connected to the server
     if (IsConnected()) {
        //Start up a new process
        System.Diagnostics.Process.Start("NAME OF YOUR APP.exe", null); 
        //and close the current process
        Environment.Exit(1);
    //If we are !connected
     } else { 
         //Tell the user to go %$# themselves 
         Console.ForegroundColor = ConsoleColor.Red;
         Log.Error("You are not currently logged on.");
         Console.ForegroundColor = ConsoleColor.Gray;
     }
}
```

and here is the is the IsConnected Method:

```
public static bool IsConnected() {
    //for all of the current TCP connections
    foreach(var c in IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections()) {
        //if the connection is established and its connect to the server 
        if (c.State.Equals(TcpState.Established) && 
            c.RemoteEndPoint.Address.ToString() == "130.211.14.80")
            //then tell everyone who wished to know about it that we are
            return true;
    }
    //of all the connections none of them are connected to the server
    return false;
}
```

So there is a very important thing to realize that because this is so hacky you wont be able to run multiple instances of the program that are connected to the server(or at least that what I think because of how the logic is set up). Because my implementation is geared more towards playing the game from console and not so much automation it works, but I would like to leave it the issue open in case a more stable method is created.

**Comment by AeonLucid** [comment]
A `Disconnect()` method is implemented in `Session`.
