### ISSUE TITLE
Inventory Delta

### ISSUE THREAD

**Issue by Lizzaran** [AeonLucid/POGOLib#25]
Inventory works so far, expect for situation where entries should get completely removed.

e.g. Pokemon Evolve, Pokemon Release.

There is no way to tell that from the inventory delta alone. 
Perhaps parse received responses and delete items based on that?

Any thoughts on that?

**Comment by Lennix** [comment]
The item delta as well as the responses don't include information to properly identify and delete the inventory item. That needs to be handled by the request and thus the calling method.

**Comment by Eliminster0** [comment]
Does Inventory include candies? I have yet to work with any of that part.

**Comment by Lizzaran** [comment]
@Eliminster0 
Yes it does. I'm gonna upload my bot in the next few days, then you can lookup on how all the stuff works.
