### ISSUE TITLE
Encounter state?

### ISSUE THREAD

**Issue by Eliminster0** [AeonLucid/POGOLib#30]
### EXPLANATION 
So once you receive the `EncounterSuccess` message, its like you are on the encounter screen where you see the pokemon dancing around taunting you and what not, and you can do the following in game actions: 

- throw a ball at it
- give it a berry
- run away from it
- take a picture of it
- turn AR on/off

The last two choices are added into it just for the sake of completeness.     

I bring this up because I am unsure if you have to go through a R&M to update the status of an encounter if it wasn't ended by a catch or the pokemon fleeing the encounter. Because after digging through the `Requests` I didn't see anything about running away from an encounter. I can see an issue with automation if you reach the condition of you have no balls :laughing: because they(the pokemon) broke out of your last ball and it(the pokemon) didn't flee. Maybe the spawn timer just runs out and the encounter auto drops, I don't know. It's just something I was pondering since I didn't see a message to run away from pokemon encounters. 

Now while you are in this Encounter state with the current pokemon does this prohibit you from initiating a second Encounter with another pokemon? Essentially being in two encounters simultaneously.  

## SKIP TO HERE IF YOU HATE READING
Is it necessary to send a request ending the encounter in the case where you have no balls left to catch them with?

**Comment by Monestic** [comment]
There is one way to find out.... test it!
