### ISSUE TITLE
Attack Gym

### ISSUE THREAD

**Issue by awmoeder** [AeonLucid/POGOLib#31]
I'm struggling to get the AttackGym method working. Does anyone know what values I must use to create a valid AttackAction?
Or is there any documentation about the desired values?

Folowing properties are available.
```cs
		public long ActionStartMs { get; set; }
		public ulong ActivePokemonId { get; set; }
		public int AttackerIndex { get; set; }
		public BattleResults BattleResults { get; set; }
		public long DamageWindowsEndTimestampMss { get; set; }
		public long DamageWindowsStartTimestampMss { get; set; }
		public int DurationMs { get; set; }
		public int EnergyDelta { get; set; }
		public BattleParticipant PlayerJoined { get; set; }
		public BattleParticipant PlayerLeft { get; set; }
		public int TargetIndex { get; set; }
		public ulong TargetPokemonId { get; set; }
		public BattleActionType Type { get; set; }
```

**Comment by awmoeder** [comment]
I am following this pasteBin ([http://pastebin.com/enDzFvUN](http://pastebin.com/enDzFvUN)), But I always receive error_invalid_actions.
Has anyone already managed to send this request?

**Comment by joshk6656** [comment]
Have you had any luck with this?

**Comment by AeonLucid** [comment]
@awmoeder Any update on this? I haven't tried out gyms myself yet.

**Comment by annongeek** [comment]
Any luck on this subject?

**Comment by awmoeder** [comment]
To be honest: I got banned from all my accounts and this has dropped my motivation to continue searching for a proper solution for this problem.

sorry... :-)
