### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by mvecchione** [AeonLucid/POGOLib#32]
Dont know if is an issue or im doing something wrong.

After event MapOnUpdate,i try to get MapCells object from SessionMap to retrieve CatchablePokemons, but is always Zero.
Here is a piece of code.
//
var cachablePokemons = session.Map.GetCatchablePokemonsSortedByDistance();
Log.Info($"catchable pokemons:{cachablePokemons.Count}");
//

I am doing something wrong??

Thans in advace

**Comment by ispyda** [comment]
Hi,

I have noticed the same thing - a project that had been working previously has suddenly stopped returning any map data.

Any thoughts anyone?

**Comment by mvecchione** [comment]
ok just do some research, there was an updated recently they have added a MapObjects checksum encryption (AES])

rest of messages are working fine...

Just keep on eye on https://github.com/AeonLucid/POGOProtos/issues/131
