### ISSUE TITLE
Uknown6 implementation

### ISSUE THREAD

**Issue by pingec** [AeonLucid/POGOLib#33]
So is anyone working on adding unknown6? Should I give it a try?

**Comment by Nacorpio** [comment]
Why are you asking for permission?
Just do it if you want to.

**Comment by AeonLucid** [comment]
I'm going to give this a shot tomorrow evening, but if you want to try it first, go ahead.
Let me know how it goes on pkre slack. :smile:

**Comment by sodanakin** [comment]
@AeonLucid I'd love to see it come back. In my opinion this is the most easy to use API. I am still learning and when I tried to use Ferox's API I couldn't even get a session to start due to the fact that nothing is documented. (As I stated still learning took me about half a day to get the bloody ISettings in and now its asking for a 2n par "apifailurestrategy" >.> ) 

In short please do :3

**Comment by DonaldBough** [comment]
Sorry for the useless comment, but I've found this to be the easiest POGO Ali as well. A lot of college kiddos would greatly appreciate the unknown6 implementation as well :)

**Comment by pingec** [comment]
So far I have not yet made it work. At least it seems not to, or perhaps my account is soft/banned. I borrowed most code from https://github.com/NECROBOTIO

I have not even tested if necrobot itself works. If anyone wants to give it a try and test/debug please go ahead and checkout https://github.com/pingec/POGOLib

To run it, Install nuggets, set user, pass and try.

The next steps would be:
 - test and ensure that necrobot itself works with that code (people said it works, but none of them compiled it from source)
- debug pogolib and compare what differs between necrobot requests and pogolib

Would be easier if we made this a group effort. Come to https://pkre.slack.com/messages/pogolib-csharp/ if you can help

**Comment by DarkAngelFR** [comment]
Just a side note : RocketAPI is working, maybe you can grab changes from there (you can have a look at the PoGo repo here : https://github.com/ST-Apps/PoGo-UWP )
hope this helps ^^

**Comment by sodanakin** [comment]
@DarkAngelFR  Yea "Working" POGOLib functioned way better in my opinion.

**Comment by Ricktza** [comment]
protolib is much better. 100%

**Comment by awmoeder** [comment]
Working updated solution in https://github.com/awmoeder/POGOLib

**Comment by Ricktza** [comment]
@awmoeder checking this now!

**Comment by Ricktza** [comment]
@awmoeder make a pull request for this repo?

**Comment by sodanakin** [comment]
@awmoeder  If it works (Going to test straight away) ill love you mate!

**Comment by awmoeder** [comment]
pull request added.

**Comment by pingec** [comment]
Haha so it was a one line fix. I knew I needed a second pair of eyes. 

Regarding the pull request - this fork is not ready for a pull-request. It has POGOProtos added as a project instead as package and the POGOProtos themselves are slightly modified (POGOProtosNetworkingSignature.cs from memory).

The POGOProtos repo should be updated to reflect the changes, then it should be re-added to this solution as a package.

Also, the whole thing needs a reformat, but the point was to make it work first.

**Comment by awmoeder** [comment]
@pingec : You are right, I will cancel the pull request. I'll let you finish the solution and you can add the pull request. Because all the credits go to you for this nice work.

**Comment by sodanakin** [comment]
@awmoeder  @pingec  Did they add 2 new arguments for the Login.GetSession ? Seeing a thing about the accesstoken and about the devicesettings.

**Comment by pingec** [comment]
@awmoeder  you can make a pull request to my repo if you want so we keep the history.

@sodanakin Who are "they"? You can take a look at the demo project, should be pretty self-explanatory how to call GetSession.

**Comment by sodanakin** [comment]
@pingec Ughh nevermind that lol I was thinking a bit weird. And ahh didn't notice the demo haha I compiled and added it, thanks! :)

**Comment by awmoeder** [comment]
"They" is @pingec .
And yes: there is an extra parameter with the deviceSettings. Bot accesstoken hasn't changed. The deviceSettings are necessary to calculate the notorious Unknown6 property.

**Comment by sodanakin** [comment]
@pingec  Just checked out the example in the demo and I love it. Very straight-forwarded and simple to use. +10

**Comment by awmoeder** [comment]
Hej @AeonLucid , 
I see that you are working on this project again. How is pokemon handling cheaters at the moment? is there still a permanent ban?
