### ISSUE TITLE
Weird issue with Items from Inventory request.

### ISSUE THREAD

**Issue by sodanakin** [AeonLucid/POGOLib#36]
`var Request_a = session.RpcClient.SendRemoteProcedureCall(new Request { RequestType = RequestType.GetInventory, RequestMessage = new GetInventoryMessage { }.ToByteString() });`
                    
`var Response= GetInventoryResponse.Parser.ParseFrom(Request_a);`

Is what I am using to send my request and get my response.
I am looping over these items with.

`foreach (var item in Response.InventoryDelta.InventoryItems)`

This works fine for pokemons and pokedex entries.
Yet if I try to do the thing below it doesn't set the value of the items to my labels.. :( 

`string ItemID = item.InventoryItemData.Item.ItemId.ToString();`
`if (ItemID.ToUpper().Equals("ITEM_POKE_BALL")) { Pokeball_Count.Text = ItemCount.ToString(); }`

I am already checking if the item isn't Null. And when I print all the items I do see these.

`{ "inventoryItemData": { "item": { "itemId": "ITEM_HYPER_POTION", "count": 50 } } }`

I am not sure whats going on =\ I'd just like to get the players inventory items count to a label lol.
Any help would be appreciated.

**Comment by AeonLucid** [comment]
You're checking the item id wrong.

Here is an example.
```csharp
foreach (var item in session.Player.Inventory.InventoryItems)
{
    if(item.InventoryItemData.Item != null)
        if (item.InventoryItemData.Item.ItemId == ItemId.ItemPokeBall)
            // "item" is a ITEM_POKE_BALL.
}
```

Also, you don't have to call `GetInventory` yourself, this is done automatically on **each** ProcedureCall.
When you send it too, that means that you're sending `GetInventoryRequest` twice in the same ProcedureCall.

**Comment by sodanakin** [comment]
@AeonLucid  Thanks! That worked! Also explains a few other errors I ran into. 

Also thanks for the 2nd tip. Didn't even realize I was sending double the amount of requests :o
