### ISSUE TITLE
Demo gives request too fast

### ISSUE THREAD

**Issue by joshk6656** [AeonLucid/POGOLib#38]
Do I need to do something to limit the requests on such a simple demo?

**Comment by sodanakin** [comment]
This is something I'd like to know too. Can we adjust the intervals ?

**Comment by Eliminster0** [comment]
I assume that you are getting the following message:
`We are sending requests too fast, sleeping for 30000 milliseconds.`

It happens when RpcClient.Startup() is called there is a flood of request sent out to the server. This is a simple way of preventing the response from falling into the status code 52.

In the RcpClient class the Startup() tell the thread to sleep for a certain amount of time in between requests like so:
```
internal bool Startup()
{
    try {
             ByteString response;
             // Send GetPlayer to check if we're connected and authenticated
             GetPlayerResponse playerResponse;
             
             do {
                  .....
             } while (!playerResponse.Success);

             Thread.Sleep(1000);      <------- //here is where we want to pause for moment 

              // Get DownloadRemoteConfig
              // ReSharper disable once RedundantAssignment
              response = SendRemoteProcedureCall(new Request
              {
                     .....
              });

              Thread.Sleep(1000);   <------- //and also here

             .....
          
       }  catch (Exception)  {
             return false;
       }
    
     return true;
}
```

This creates a lag time from once you launch the program and when you break into the handle commands loop, obviously this causes it to wait for two seconds, it think if you cut them both in half you should be fine.

**Comment by Recio** [comment]
@sodanakin you can adjust the interval in the Configuration.cs file

**Comment by Eliminster0** [comment]
@Recio the value that you are referencing is the amount of time that you timeout for **after** you submit too many requests. It does nothing to limit actual time in between request.

**Comment by Recio** [comment]
@Eliminster0 you're absolutely right, I misread what you wanted, my bad.

**Comment by Eliminster0** [comment]
@Recio you are gud mate, what you suggested would work also as far as returning control to the user just not what actually causes the timeout to fire

**Comment by Eliminster0** [comment]
After running the new Demo, I noticed that the request in the Main function should be either be moved to its own function so the user can call or just sleep the thread right before it:

```
public static void Main(string[] args)   {
            Logger.Info("Booting up.");
            Logger.Info("Type 'q', 'quit' or 'exit' to exit.");
            Console.Title = "POGO Demo";

            var arguments = new Arguments();
            if (Parser.Default.ParseArguments(args, arguments))
            {
                 .....

                // Send initial requests and start HeartbeatDispatcher
                session.Startup();

                Thread.Sleep(500);  <--- //sleep here or just move the request below 

                var fortDetailsBytes = session.RpcClient.SendRemoteProcedureCall(new Request
                {
                    RequestType = RequestType.FortDetails,
                    RequestMessage = new FortDetailsMessage
                    {
                        FortId = "e4a5b5a63cf34100bd620c598597f21c.12",
                        Latitude = 51.507335,
                        Longitude = -0.127689
                    }.ToByteString()
                });
                var fortDetailsResponse = FortDetailsResponse.Parser.ParseFrom(fortDetailsBytes);

                Console.WriteLine(JsonConvert.SerializeObject(fortDetailsResponse, Formatting.Indented));
            }

            HandleCommands();
        }
```

**Comment by joshk6656** [comment]
@Eliminster0 could you tell me how to disable debug log printing in the demo?

**Comment by Recio** [comment]
@joshk6656 quick and easy way, but no the best, is to comment out all the body's static methods in Logger.cs

(Debug, Notice, Error, Info, Warn)

**Comment by Recio** [comment]
@joshk6656 or comment the 'Console.WriteLine($"{timestamp,-10}{logLevel,-8}{message}");' @ line 51

**Comment by Eliminster0** [comment]
@joshk6656 I don't recommend doing this and haven't I tried this myself, but I am pretty sure if you just line comment the Output function in  POGOLib/POGOLib/Logging/Logger.cs you could accomplish what you want. Like so.


```
private static void Output(LogLevel logLevel, string message)
{
          /*       <---- // add this

            if (logLevel < LoggerConfiguration.MinimumLogLevel) return;

            var foregroundColor = LoggerConfiguration.DefaultForegroundColor;
            var backgroundColor = LoggerConfiguration.DefaultBackgroundColor;
            var timestamp = DateTime.Now.ToString("HH:mm:ss");

            if (LoggerConfiguration.LogLevelColors.ContainsKey(logLevel))
            {
                var colors = LoggerConfiguration.LogLevelColors[logLevel];

                foregroundColor = colors.ForegroundColor;
                backgroundColor = colors.BackgroundColor;
            }

            Console.ForegroundColor = foregroundColor;
            Console.BackgroundColor = backgroundColor;
            Console.WriteLine($"{timestamp,-10}{logLevel,-8}{message}");
            Console.ResetColor();

            */       <--- and this
}

```

I believe this works try this and let me know if it does.

**Comment by zone117x** [comment]
This issue is probably fixed or improved with async/await in the PCL branch

**Comment by zone117x** [comment]
This should fix the timing issues https://github.com/AeonLucid/POGOLib/commit/c79603d0120d95d55ec33fd47de47f5eea5873d5

**Comment by joshk6656** [comment]
I was hoping that I could utilize the debug argument to disable the message, apparently not. I commented out one line in logger.cs

public static void Debug(string message)
        {
            //Output(LogLevel.Debug, message); //commented out this line.
        }

**Comment by joshk6656** [comment]
I am using the others to write useful things (for me), I will just my debug
comment when i actually need to debug.

Great project btw guys.

**Comment by zone117x** [comment]
The new code allows you to specify the log provider.
