### ISSUE TITLE
Exception on getMapObjects proto

### ISSUE THREAD

**Issue by Lo11o2** [AeonLucid/POGOLib#46]
Hi everyone,
I'm stucked on this terrible exception, that's my code:

`var session = Login.GetSession("user", "password", LoginProvider.PokemonTrainerClub, 45.447664, 9.135188);
            session.Startup();

```
        System.Threading.Thread.Sleep(10000);

        var getMapObjectsBytes = session.RpcClient.SendRemoteProcedureCall(new Request
        {
            RequestType = RequestType.GetMapObjects,
            RequestMessage = new GetMapObjectsMessage
            {
                Latitude = 45.447664,
                Longitude = -0.127689
            }.ToByteString()
        });
        var getMapObjectsResponse = GetMapObjectsResponse.Parser.ParseFrom(getMapObjectsBytes);`
```

The exception says "There were only 1 response, we're expecting 5"...
Ofc it's a bad request for give this kind of error, but where am i missing D:

**Comment by Recio** [comment]
I dunno

A couple of days ago the server also gave me that error randomly, but then it magically fixed itself.
