### ISSUE TITLE
Converting to netstandard 1.0

### ISSUE THREAD

**Issue by AeonLucid** [AeonLucid/POGOLib#47]
I want to rewrite/fix/convert POGOLib and maintain it better.

Last thing me and @zone117x worked on was the `proper-pcl` branch but I'd love to go for **netstandard 1.0** instead and use the changes we made for the `proper-pcl` branch.

Problems:
- It would break code for a lot of users. (Not even sure if the `master` branch works anyway).
- No idea how to build a netstandard project with AppVeyor.
- No idea how to deploy a netstandard project to NuGet.
- I don't want to just get rid of the `proper-pcl` branch but use most of the changes.

What I want to do (based on current `master`):
- Make the library async so it doesn't block.
- Convert to **netstandard 1.0**.
- Implement throttling for requests.
- Better exception message ([example of a bad one](https://github.com/AeonLucid/POGOLib/blob/7ea34e7d5a6d93f6b24ad0bf0783b3e0fb1a0d03/POGOLib/Net/RPCClient.cs#L414)).

I'll be doing this on a `development` branch but I'm looking for some thoughts about this before I start messing around.

**Comment by gadzair** [comment]
So I can help as well, but my #1 consideration is that it works flawlessly in my Xamarin Studio mac environment with Xamarin Forms. In the past, whenever I've submitted very basic PRs to fix my Xamarin Forms compilation issues and you guys didn't take any of them. I had therefore had to abandon attempts to stay in sync with POGOLib and continued adding various features to my own fork, such as request throttling. But if you're willing to ensure that your branch works fully in my environment, then I'd be happy to contribute.

**Comment by kmbriedis** [comment]
Problem 1 isn't really a problem, it is their own fault if they referenced their project to master branch (not commit, release etc.), they cannot expect that the branch will never be changed.

With these changes planned, where should I add some missing features? Like hatched egg event https://github.com/AeonLucid/POGOLib/blob/master/POGOLib/Net/RPCClient.cs#L480

**Comment by wertzui** [comment]
Why do you want to base it on the current master branch and not on the proper-pcl branch? the proper-pcl branch is already async and has a lot more bugfixes than the master branch. Also the newest Protos must be included. As for .Net Standard go ahead, would love to see that :)

**Comment by AeonLucid** [comment]
@gadzair Yeah the project was a bit messy with the `proper-pcl` branch, it took longer than expected. I'll be communicating with you on discord to make sure the converted (and kinda rewritten) project works for you when it's time.

@kmbriedis I'd like to wait with implementing "new" features at the moment, I want to convert / fix and get stable first.

@wertzui That's not what I meant to say, woops. I meant, if you _look_ at `master`, I want to do x and x. I'll be working of the `proper-pcl` branch since it already has most of those things.

**Comment by AeonLucid** [comment]
Created the branch: https://github.com/AeonLucid/POGOLib/tree/netstandard-convert

**Comment by AeonLucid** [comment]
Converted two libraries and put them on NuGet.

- https://github.com/AeonLucid/PokemonGoEncryptSharp.NetStandard1
- https://github.com/AeonLucid/GeoCoordinate.NetStandard1

**Comment by AeonLucid** [comment]
Pushed, it's kinda stable. Not done yet!
https://github.com/AeonLucid/POGOLib/tree/netstandard-convert

**Comment by wertzui** [comment]
Could you integrate an automated Nuget build, as it is much easier to include a nuget Package than a Git submodule

**Comment by AeonLucid** [comment]
This library is now running on .netstandard 1.1. Closing this issue. 😄
