### ISSUE TITLE
Unable to refresh authorization

### ISSUE THREAD

**Issue by trembon** [AeonLucid/POGOLib#59]
After keeping the connection up for maybe 15 minutes the API starts to return 0 results on the map.
Then it tries to reauthenticate, which it seems to fail.

The log from your output is the following:
Sending RPC Request: 'GetMapObjects, CheckChallenge, GetHatchedEggs, GetInventory, CheckAwardedBadges, DownloadSettings'
Received StatusCode 102, reauthenticating.
Authenticated through PTC.
Sending RPC Request: 'GetMapObjects, CheckChallenge, GetHatchedEggs, GetInventory, CheckAwardedBadges, DownloadSettings'
Received StatusCode 102, reauthenticating.

After this, the last two lines just keeps repeating in a loop until I close the application. If i restart the application the API returns results directly, so it does not seems to be a softban thing.

**Comment by AeonLucid** [comment]
This was fixed in 1.2.0 (https://github.com/AeonLucid/POGOLib/commit/35ce3f1c2f51bde1e75ba10033c3daadab7bba3a), can you confirm?

**Comment by trembon** [comment]
It does not generate the error anymore, but it starts giving empty results (both forts and pokemon) after the same timespan.
I'll do some testing and see if it's something in my code regarding the empty results.

**Comment by trembon** [comment]
I tried using the library with standing still on one cordinate, and with the same result. I'm not getting any errors and after the same time frame I start to get 0 results.
Dont know if its related to the problem with authentication, but it seems to work after I restart the app, not always, but sometimes.

**Comment by AeonLucid** [comment]
@trembon Can you open up a new issue for this? I'll look into it.
