### ISSUE TITLE
Why captcha'd ?

### ISSUE THREAD

**Issue by pogarek** [AeonLucid/POGOLib#74]
Hi

This issue is , probably, not a problem with POGOLib, rather a mistake in my approach. But I have no idea how to solve it :-( 

I have a simple tool (using 1.3alpha api with hashing key) , that checks for ecounterid, spawnlocationid and IV oif pokemon. However I get a lot of captchas... or no forts returned. 

Approach used:
if session == null => then GetSession +StartupAsync()  on start location. 
Then Player.SetCoordinates to pokemon location , session.RpcClient.RefreshMapObjectsAsync(), and  Player.SetCoordinates back to start location. More or less - nothing else..

Any ideas ? Thank you.

**Comment by AeonLucid** [comment]
Can you check with POGOLib 1.3.0?
