### ISSUE TITLE
Error authenticating with google

### ISSUE THREAD

**Issue by kddeisz** [AeonLucid/POGOLib#75]
Hi there! Great work on this. Wondering if you can help me out. Just trying to do a basic GetInventory request and parse it as JSON. I'm getting the error:

```
System.ArgumentNullException has been thrown
Value cannot be null.
Parameter name: data
```

My code is:

```c#
using System;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json;

using POGOLib.Official.LoginProviders;
using POGOLib.Official.Net;
using POGOLib.Official.Net.Authentication;
using POGOLib.Official.Net.Authentication.Data;

using POGOProtos.Networking.Requests;
using POGOProtos.Networking.Requests.Messages;
using POGOProtos.Networking.Responses;

namespace POGOIVs
{
	public class Runner
	{
		public static void Main(string[] args)
		{
			Run(args).GetAwaiter().GetResult();
		}

		private static async Task Run(string[] args)
		{
			POGOLib.Official.Configuration.IgnoreHashVersion = true;
			Console.Title = "POGOIVs";

			const string usernameStr = "...";
			const string passwordStr = "...";
			ILoginProvider loginProvider = new GoogleLoginProvider(usernameStr, passwordStr);

			var latitude = ...;
			var longitude = ...;
			var session = await Login.GetSession(loginProvider, latitude, longitude);
			await session.StartupAsync();
		}
	}
}
```

I have 2 factor turned off for this. Can anyone help me out? Thanks!

**Comment by karaagacsk** [comment]
I have this same issue when pulling in the nuget packages.
However using the demo provided in the solution - I dont get the ArgumentNullException. 

Will try to look into why - but in the mean time..

I have written my IV solution in the demo - branched off master as its now removed from dev
https://github.com/karaagacsk/POGOLib/tree/POGODemoIVWithEvolutionCalc

**Comment by AeonLucid** [comment]
Please re-open the issue if it happens with POGOLib 1.3.0 too.

**Comment by rik91** [comment]
Hi !
The same issue happens with POGOLib 1.3.0.
I try with your Demo.ConsoleApp application and there is the same problem.

**Comment by AeonLucid** [comment]
I'll take a look tomorrow! @rik91

**Comment by rik91** [comment]
any news ?

**Comment by PeterDM65** [comment]
Hi,

i'am trying to use your demo app but get the following error (in Dutch):
System.ArgumentNullException
Waarde kan niet null zijn.
Parameternaam: data
Translation: 
Value cannot be null
Parametername:data

i'am using the following versions of POGO
  <package id="POGOLib.Official" version="1.5.3" targetFramework="net452" />
  <package id="POGOLib.Official.Google" version="1.0.0" targetFramework="net452" />
  <package id="POGOProtos.NetStandard1" version="2.13.0" targetFramework="net452" />

And use the 'GoogleLoginProvider'

Any suggestions ?
