### ISSUE TITLE
RpcEncryption.cs  [BuildLocationFixes method]

### ISSUE THREAD

**Issue by lguilhermee** [AeonLucid/POGOLib#80]
StackTrace = "   at System.Random.Next(Int32 minValue, Int32 maxValue)\r\n   at POGOLib.Official.Net.RpcEncryption.BuildLocationFixes(RequestEnvelope requestEnvelope, Int64 timestampSinceStart)\r\n   at POGOLib.Official.Net.RpcEncryption.<GenerateSignatureAsync>d__8.Mov... 

https://github.com/AeonLucid/POGOLib/blob/b364e09e2e4bf500cc9598d2ec2f0a5aacdbcebb/POGOLib.Official/Net/RpcEncryption.cs

Sometimes it returning a minValue bigger than maxValue returning a error.

**"Min value can't be great than max value"**

**Comment by jjskuld** [comment]
Yup I saw this error a few times as well.

**Comment by AeonLucid** [comment]
It would be really helpful if you could provide the full stacktrace next time.
